In [1]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

In [3]:
def to_standard_units(x_given):
    return (x_given - np.mean(x_given))/np.std(x_given)

def from_standard_units(x_standard, mean, std):
    return std*x + mean
    
def make_correlated_data(r):
    x = np.random.normal(0, 1, 179)
    z = np.random.normal(0,1,179)
    y = r*x + np.sqrt(1-r**2)*z
    return x,y

def make_r_table(r):
   #  np.random.seed(8)
    x,y = make_correlated_data(r)
    x = standard_units(x)
    y = standard_units(y)
    return Table().with_columns(f'x\n r = {r}',x,'y',y)

def draw_r_table(r):
    my_table = make_r_table(r)
    my_table.scatter('x','y')

def calculate_r_from_table(tbl, x_column_name, y_column_name):
    x_standard = to_standard_units(tbl.column(x_column_name))
    y_standard = to_standard_units(tbl.column(y_column_name))
    return np.average(x_standard * y_standard)

def calculate_r_from_arrays(x_array, y_array):
    x_standard = to_standard_units(x_array)
    y_standard = to_standard_units(y_array)
    return np.average(x_standard * y_standard)                  

def regression_line_in_given_units(x_array, y_array):
    r = calculate_r_from_arrays(x_array, y_array)
    m = r*np.std(y_array)/np.std(x_array)
    b = np.average(y_array) - m*np.average(x_array)
    return m,b
    
def apply_regression_line_to_table(tbl,x_column_name,y_column_name):
    x_array = tbl.column(x_column_name)
    y_array = tbl.column(y_column_name)
    m,b = regression_line_in_given_units(x_array,y_array)
    predictions = m*x_array + b
    return predictions
    
def draw_line(slope=0, intercept=0,x=make_array(-4,4), color = 'r'):
    y = x*slope + intercept
    plots.plot(x,y,color=color)
    
def draw_regression_graph(r):
    tbl = make_r_table(r)
    tbl.scatter('x')
    draw_line(1)
    draw_line(r,color='g')

In [4]:
sales = Table.read_table('houses_reduced.csv')

In [5]:
sales.show(3)

In [21]:
standard_units = sales.apply(to_standard_units)
labels = sales.labels[1:]

for label in sales.labels[1:]:
    standard_units = to_standard_units(sales.column(label))
    sales = sales.with_column(label, standard_units)

sales.show(3)
sales.to_csv('houses_reduced.csv')

In [17]:
sales = Table.read_table('houses_reduced.csv')
sales.show(3)

In [ ]:
sales.apply(to_standard_units,'1st Flr SF')