In [1]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

In [3]:
names = make_array('Celtics','Lakers','Nets')
divisions = make_array('Atlantic','Pacific','Atlantic')
conferences = make_array('Eastern', 'Western', 'Eastern')
arenas = make_array(1,2,3)
teams = Table().with_columns('name',names, 'division',divisions, 'conference',conferences, 'arena',arenas)

In [4]:
teams

name    | division | conference | arena
Celtics | Atlantic | Eastern    | 1
Lakers  | Pacific  | Western    | 2
Nets    | Atlantic | Eastern    | 3

In [5]:
teams.where('conference','Eastern').group('division')

division | count
Atlantic | 2